# Generated by Django 5.2.5 on 2025-10-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=255, unique=True)),
                ('server_name', models.CharField(max_length=255)),
                ('server_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('member_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Discord сервер',
                'verbose_name_plural': 'Discord серверы',
            },
        ),
    ]
