# Generated by Django 5.2.5 on 2025-10-04 09:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('DiscordBot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OsuApiApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('requests_count', models.IntegerField(default=0)),
                ('error_times', models.JSONField(default=list)),
                ('reset_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('token_expires_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OsuPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_rank', models.IntegerField(blank=True, null=True)),
                ('country_rank', models.IntegerField(blank=True, null=True)),
                ('pp', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('playcount', models.IntegerField(default=0)),
                ('level', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('osu', 'osu!'), ('taiko', 'osu!taiko'), ('fruits', 'osu!catch'), ('mania', 'osu!mania')], default='osu', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osu_performances', to='Accounts.unauthorizedosuusers')),
            ],
            options={
                'verbose_name': 'Рейтинг osu!',
                'verbose_name_plural': 'Рейтинги osu!',
                'unique_together': {('user', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='ServerMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='DiscordBot.discordserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник сервера',
                'verbose_name_plural': 'Участники серверов',
                'unique_together': {('user', 'server')},
            },
        ),
    ]
