# Generated by Django 5.2.5 on 2025-10-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='osuapiapplication',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='osuapiapplication',
            name='token_expires_at',
        ),
    ]
