# Generated by Django 5.2.5 on 2025-10-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0002_remove_osuapiapplication_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osuapiapplication',
            name='error_times',
            field=models.JSONField(default=list, null=True),
        ),
    ]
