# Generated by Django 5.2.5 on 2025-10-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0003_alter_osuapiapplication_error_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osuapiapplication',
            name='error_times',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
