# Generated by Django 5.2.5 on 2025-10-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboard', '0004_alter_osuapiapplication_error_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='osuapiapplication',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='osuapiapplication',
            name='token_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='osuapiapplication',
            name='error_times',
            field=models.JSONField(default=list),
        ),
    ]
